default:
  tags: [linux,docker]
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu24.04:latest

stages:
  - build
  - static-analysis
  - pages


linux-ac-current:
  stage: build
  script:
    - sh build/gitlab-ci autoconf
  after_script:
    - 'cat autoconf-build/test/test-suite.log'
  artifacts:
    name: distribution
    paths:
    - distribution

linux-ac-old:
  stage: build
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu22.04:latest
  script:
    - sh build/gitlab-ci autoconf-minimal
  after_script:
    - 'cat autoconf-build/test/test-suite.log'

linux-cmake-make-current:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

linux-cmake-make-current-static:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release static

linux-cmake-ninja-current:
  stage: build
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug

linux-cmake-make-old:
  stage: build
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu22.04:latest
  script:
    - sh build/gitlab-ci cmake "Unix Makefiles" Release

freebsd15-release:
  stage: build
  tags: [freebsd15]
  script:
    - sh build/gitlab-ci cmake Ninja Release

freebsd15-debug:
  stage: build
  tags: [freebsd15]
  script:
    - sh build/gitlab-ci cmake Ninja Debug

macos26-release:
  stage: build
  tags: [macos26]
  script:
    - sh build/gitlab-ci cmake Ninja Release

macos26-debug:
  stage: build
  tags: [macos26]
  script:
    - sh build/gitlab-ci cmake Ninja Debug


coverity:
  stage: static-analysis
  image: registry.gitlab.com/libtiff/libtiff-ci-ubuntu24.04-coverity:latest
  script:
    - sh build/gitlab-ci coverity "Ninja" Debug
  only:
    refs:
      - master

pages:
  stage: pages
  script:
    - sh build/gitlab-ci cmake "Ninja" Debug
    - cp -r cmake-install/share/doc/tiff/manual/html public
  artifacts:
    name: $CI_PROJECT_NAME-$CI_JOB_NAME
    paths:
    - public
  only:
  - master
